/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author noahp, hashim271 N01723647
 */
public class BakeryOrderForm extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(BakeryOrderForm.class.getName());

    /**
     * Creates new form BakeryOrderForm
     */
    public BakeryOrderForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sizeGroup = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cmbCake = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        rSmall = new javax.swing.JRadioButton();
        rMedium = new javax.swing.JRadioButton();
        rLarge = new javax.swing.JRadioButton();
        chkFreeDelivery = new javax.swing.JCheckBox();
        btnSave = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Customer Name :");

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });

        jLabel2.setText("Phone Number :");

        jLabel3.setText("Cake Type :");

        cmbCake.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Apple", "Carrot", "Cheesecake", "Chocolate", "Coffee", "Opera", "Tiramisu", " " }));

        jLabel4.setText("Size : ");

        sizeGroup.add(rSmall);
        rSmall.setText("Small");
        rSmall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rSmallActionPerformed(evt);
            }
        });

        sizeGroup.add(rMedium);
        rMedium.setText("Medium");
        rMedium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rMediumActionPerformed(evt);
            }
        });

        sizeGroup.add(rLarge);
        rLarge.setText("Large");
        rLarge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rLargeActionPerformed(evt);
            }
        });

        chkFreeDelivery.setText("Lives within free delivery area");
        chkFreeDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkFreeDeliveryActionPerformed(evt);
            }
        });

        // SAVE EVENT
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        // QUIT EVENT
        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {

            public void actionPerformed(java.awt.event.ActionEvent evt) {

                btnQuitActionPerformed(evt);
            }

        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel3,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel4,
                                                                javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(6, 6, 6)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(lblStatus)
                                                                        .addComponent(jLabel2))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(cmbCake, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(rSmall)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(rMedium)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(rLarge))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(62, 62, 62)
                                                .addComponent(chkFreeDelivery)))
                                .addContainerGap(113, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuit)
                                .addGap(18, 18, 18)
                                .addComponent(btnSave)
                                .addGap(127, 127, 127)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel1)
                                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(cmbCake, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(rSmall)
                                        .addComponent(rMedium)
                                        .addComponent(rLarge))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chkFreeDelivery)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnSave)
                                        .addComponent(btnQuit))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59,
                                        Short.MAX_VALUE)
                                .addComponent(lblStatus)
                                .addGap(75, 75, 75)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtNameActionPerformed

    private void rSmallActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rSmallActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rSmallActionPerformed

    private void rMediumActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rMediumActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rMediumActionPerformed

    private void rLargeActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_rLargeActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_rLargeActionPerformed

    private void chkFreeDeliveryActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_chkFreeDeliveryActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_chkFreeDeliveryActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnSaveActionPerformed

        // Get the users input
        String name = txtName.getText().trim();
        String phone = txtPhone.getText().trim();
        String cake = (String) cmbCake.getSelectedItem();
        String size = "";

        // Size of cake
        if (rSmall.isSelected())
            size = "Small";
        else if (rMedium.isSelected())
            size = "Medium";
        else if (rLarge.isSelected())
            size = "Large";

        // Check for free delivery
        boolean delivery = chkFreeDelivery.isSelected();

        // Making sure it is not empty AKA Validation for Person 3!!
        if (name.isEmpty() || phone.isEmpty() || size.isEmpty() || cake == null || cake.isBlank()) {

            lblStatus.setText("Please fill out all the required fields before clicking on save!");
            return;
        }

        // Resetting the fields to blank
        txtName.setText("");
        txtPhone.setText("");
        cmbCake.setSelectedIndex(0);
        sizeGroup.clearSelection();
        chkFreeDelivery.setSelected(false);

        txtName.requestFocus(); // Go back to the first field

    }

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {

        // Show confirmation to prevent accidental exit
        int confirm = javax.swing.JOptionPane.showConfirmDialog(

                this,
                "Are you sure you want to Quit???",
                "Confirm Exit",
                javax.swing.JOptionPane.YES_NO_OPTION // Given Options

        );

        // If user clicked 'Yes', close window and exit app
        if (confirm == javax.swing.JOptionPane.YES_OPTION) {

            dispose();
            System.exit(0);

        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new BakeryOrderForm().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox chkFreeDelivery;
    private javax.swing.JComboBox<String> cmbCake;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JRadioButton rLarge;
    private javax.swing.JRadioButton rMedium;
    private javax.swing.JRadioButton rSmall;
    private javax.swing.ButtonGroup sizeGroup;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables
}
